version: '3'

services:

  # AS #
  AS-router:
    image: router
    volumes:
      - ./data/AS-router:/data
    networks:
      AS:
        ipv4_address: 120.0.32.5
      interco:
        ipv4_address: 120.0.38.2

  AS-dmz-router:
    image: router
    volumes:
      - ./data/AS-dmz-router:/data
    networks:
      AS-DMZ:
        ipv4_address: 120.0.34.2
      AS:
        ipv4_address: 120.0.32.2

  AS-dns:
    image: dns-server
    volumes:
      - ./data/AS-dns:/data
    networks:
      AS-DMZ:
        ipv4_address: 120.0.34.3
  
  interco-routeur:
    image: router
    volumes:
      - ./data/interco-routeur:/data
    networks:
      interco:
        ipv4_address: 120.0.38.3


  # Partie Entreprise de l'AS #
  acces-entreprise-router:
    image: router
    volumes:
      - ./data/acces-entreprise-router:/data
    networks:
      acces-entreprise:
        ipv4_address: 120.0.36.2
      AS:
        ipv4_address: 120.0.32.3
  
  entreprise-box:
    image: box
    volumes:
      - ./data/entreprise-box:/data
    networks:
      entreprise:
        ipv4_address: 10.128.0.2
      acces-entreprise:
        ipv4_address: 120.0.36.3

  entreprise-dns:
    image: dns-server
    volumes:
      - ./data/entreprise-dns:/data
    networks:
      entreprise-dmz:
        ipv4_address: 
          10.0.0.3

  entreprise-client:
    image: client
    dns: 10.0.0.3
    volumes:
      - ./data/entreprise-client:/data
    networks:
      entreprise:
          ipv4_address: 10.128.0.4

  entreprise-dmz-router:
    image: router
    volumes:
      - ./data/entreprise-dmz-router:/data
    networks:
      entreprise-dmz:
        ipv4_address: 10.0.0.2
      entreprise:
        ipv4_address: 10.128.0.3


  # Partie Client de l'AS #
  acces-client-router:
    image: router
    volumes:
      - ./data/acces-client-router:/data
    networks:
      acces-client:
        ipv4_address: 120.0.40.2
      AS:
        ipv4_address: 120.0.32.4

  client-box:
    image: box
    volumes:
      - ./data/client-box:/data
    networks:
      client:
        ipv4_address: 192.168.0.2
      acces-client:
        ipv4_address: 120.0.40.3

  client-machine:
    image: client
    dns: 120.0.34.3
    volumes:
      - ./data/client-machine:/data
    networks:
      client:
        ipv4_address: 192.168.0.3


networks:
  AS:
    ipam:
      config:
        - subnet: 120.0.32.0/23

  AS-DMZ:
    ipam:
      config:
        - subnet: 120.0.34.0/23

  acces-entreprise:
    ipam:
      config:
        - subnet: 120.0.36.0/23
  
  acces-client:
    ipam:
      config:
        - subnet: 120.0.40.0/21

  client:
    ipam:
      config:
        - subnet: 192.168.0.0/24

  entreprise:
    ipam:
      config:
        - subnet: 10.128.0.0/9
  
  entreprise-dmz:
    ipam:
      config:
        - subnet: 10.0.0.0/9

  interco:
    ipam:
      config:
        - subnet: 120.0.38.0/23