version: '3'

services:

  # AS #
  AS-router:
    extends:
      file: ./docker-compose-common.yml
      service: base
    image: router
    volumes:
      - ./data/AS-router:/data
    networks:
      AS:
        ipv4_address: 120.0.32.4

  AS-dmz-router:
    extends:
      file: ./docker-compose-common.yml
      service: base
    image: router
    volumes:
      - ./data/AS-dmz-router:/data
    networks:
      AS-DMZ:
        ipv4_address: 120.0.34.1
      AS:
        ipv4_address: 120.0.32.1

  AS-dns:
    extends:
      file: ./docker-compose-common.yml
      service: base
    image: dns
    volumes:
      - ./data/AS-dns:/data
    networks:
      AS-DMZ:
        ipv4_address: 120.0.34.2

  # Partie Entreprise de l'AS #
  acces-entreprise-router:
    extends:
      file: ./docker-compose-common.yml
      service: base
    image: router
    volumes:
      - ./data/acces-entreprise:/data
    networks:
      acces-entreprise:
        ipv4_address: 120.0.36.1
      AS:
        ipv4_address: 120.0.32.2
  
  entreprise-box:
    extends:
      file: ./docker-compose-common.yml
      service: base
    image: box
    volumes:
      - ./data/entreprise-router:/data
    networks:
      entreprise:
        ipv4_address: 10.64.0.1
      acces-entreprise:
        ipv4_address: 120.0.36.2

  entreprise-dns:
    extends:
      file: ./docker-compose-common.yml
      service: base
    image: dns
    volumes:
      - ./data/entreprise-dns:/data
    networks:
      entreprise-dmz:
        ipv4_address: 
          10.0.0.2

  entreprise-client:
    extends:
      file: ./docker-compose-common.yml
      service: base
    image: client
    dns: 10.0.0.2
    volumes:
      - ./data/entreprise-client:/data
    networks:
      - entreprise:
          ipv4_address: 10.64.0.3

  entreprise-dmz-router:
    extends:
      file: ./docker-compose-common.yml
      service: base
    image: router
    volumes:
      - ./data/entreprise-dmz-router:/data
    networks:
      entreprise-dmz:
        ipv4_address: 10.0.0.1
      entreprise:
        ipv4_address: 10.64.0.2


  # Partie Client de l'AS #
  acces-client-router:
    extends:
      file: ./docker-compose-common.yml
      service: base
    image: router
    volumes:
      - ./data/acces-client-router:/data
    networks:
      acces-client:
        ipv4_address: 120.0.40.1
      AS:
        ipv4_address: 120.0.32.3

  client-box:
    extends:
    file: ./docker-compose-common.yml
    service: base
    image: box
    volumes:
      - ./data/client-box:/data
    networks:
      client:
        ipv4_address: 192.168.0.1
      acces-client:
        ipv4_address: 120.0.32.1

  client-machine:
    extends:
      file: ./docker-compose-common.yml
      service: base
    image: client
    dns: 120.0.34.2
    volumes:
      - ./data/client-machine:/data
    networks:
      client:
        ipv4_address: 192.168.0.2


networks:
  AS:
    ipam:
      config:
        - subnet: 120.0.32.0/23

  AS-DMZ:
    ipam:
      config:
        - subnet: 120.0.34.0/23

  acces-entreprise:
    ipam:
      config:
        - subnet: 120.0.36.0/22
  
  acces-client:
    ipam:
      config:
        - subnet: 120.0.40.0/21

  client:
    ipam:
      config:
        - subnet: 192.168.0.0/24

  entreprise:
    ipam:
      config:
        - subnet: 10.64.0.0/9
  
  entreprise-dmz:
    ipam:
      config:
        - subnet: 10.0.0.0/9